/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sir.ui;

import com.pixelmed.dicom.DicomException;
import java.util.ArrayList;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sir.nf.DMR;
import sir.nf.Dates;
import sir.nf.Examen;
import sir.nf.Factory;
import sir.nf.MedicalStaff;
import sir.nf.ExamenType;
import com.pixelmed.display.SingleImagePanel;
import com.pixelmed.display.SourceImage;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sir.nf.Function;
import sir.nf.Impression;

/**
 *
 * @author solenn
 */
public class AccueilPatient extends javax.swing.JFrame {

    private MedicalStaff medecinCo;
    private ArrayList<DMR> listeDMR;
    private ArrayList<MedicalStaff> listeStaff;
    private ArrayList<Examen> listeExam;
    private DMR dmr;
    private Examen examen;

    private String[] liste;

    /**
     * Creates new customizer AccueilPatient
     */
    public AccueilPatient(MedicalStaff medecinCo, DMR dmr) {
        initComponents();
        this.setTitle("Accueil DMR");
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);

        jFrameAide.setSize(700, 600);
        jFrameAide.setVisible(false);
        jFrameAide.setResizable(false);

        this.medecinCo = medecinCo;
        listeStaff = Factory.getListeMedecin();
        listeDMR = Factory.getListePatient();
        this.dmr = dmr;
        this.examen = null;
        this.listeExam = dmr.recupExamen();

        id.setText(Integer.toString(medecinCo.getId()));
        name.setText(medecinCo.getName() + " " + medecinCo.getSurname());
        fonction.setText(medecinCo.getFunction().toString());
        String format = "dd/MM/yy";
        java.text.SimpleDateFormat formater = new java.text.SimpleDateFormat(format);
        java.util.Date d = new java.util.Date();
        date.setText(formater.format(d));

        ident.setText(Integer.toString(dmr.getId()));
        genre.setText(dmr.getGender().toString());
        nomPat.setText(dmr.getName());
        prenomPat.setText(dmr.getSurname());
        dateNPat.setText(dmr.getBirthday().afficherDateN());

        Object[][] dataExam = new Object[listeExam.size()][8];
        this.liste = new String[8];
        this.liste[0] = "Prioritaire";
        this.liste[1] = "Id Examen";
        this.liste[2] = "Type";
        this.liste[3] = "Date Examen";
        this.liste[4] = "Prescripteur";
        this.liste[5] = "Responsable Radio";
        this.liste[6] = "Compte-Rendu";
        this.liste[7] = "Lien PACS";
        for (int i = 0; i < listeExam.size(); i++) {
            if (listeExam.get(i).isPrioritaire()) {
                dataExam[i][0] = "V";
            } else {
                dataExam[i][0] = " ";
            }
            dataExam[i][1] = listeExam.get(i).getId_examen();
            dataExam[i][2] = listeExam.get(i).getExamenType().toString();
            dataExam[i][3] = listeExam.get(i).getDate();
            dataExam[i][4] = listeExam.get(i).getPrescripteur();
            dataExam[i][5] = listeExam.get(i).getResponsableRadio();
            if (listeExam.get(i).getReport() != null) {
                dataExam[i][6] = "V";
            } else {
                dataExam[i][6] = "F";
            }
            if (listeExam.get(i).getPacsID() != null) {
                dataExam[i][7] = "V";
            } else {
                dataExam[i][7] = "F";
            }
        }
        DefaultTableModel dtm = new DefaultTableModel(dataExam, liste);
        jTableExamen.setModel(dtm);
        jTableExamen.getColumnModel().getColumn(0).setCellRenderer(new CouleurCellRenderer());
        jTableExamen.getColumnModel().getColumn(6).setCellRenderer(new ImageCellRenderer());
        jTableExamen.getColumnModel().getColumn(7).setCellRenderer(new ImageCellRenderer());
        RowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dtm);
        jTableExamen.setRowSorter(sorter);

        jSplitImage.setOneTouchExpandable(true);
        jSplitImage.setDividerLocation(100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameAide = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        fonction = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonAjouterExamen = new javax.swing.JButton();
        jButtonDeco = new javax.swing.JButton();
        jButtonAide = new javax.swing.JButton();
        jButtonAccueil = new javax.swing.JButton();
        jButtonAjouterPatient = new javax.swing.JButton();
        jButtonAjouterPersonnel = new javax.swing.JButton();
        jButtonAjouterCR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ident = new javax.swing.JLabel();
        genre = new javax.swing.JLabel();
        nomPat = new javax.swing.JLabel();
        prenomPat = new javax.swing.JLabel();
        dateNPat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableImage = new javax.swing.JTable();
        jButtonNumImage = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExamen = new javax.swing.JTable();
        jRadioButtonDate = new javax.swing.JRadioButton();
        jButtonRechercher = new javax.swing.JButton();
        jTextFieldJour = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<ExamenType>(ExamenType.values());
        jRadioButtonType = new javax.swing.JRadioButton();
        jTextFieldID = new javax.swing.JTextField();
        jRadioButtonID = new javax.swing.JRadioButton();
        jTextFieldAnnee = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMois = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jSplitImage = new javax.swing.JSplitPane();
        Image2 = new javax.swing.JInternalFrame();
        Image1 = new javax.swing.JInternalFrame();
        jPanel10 = new javax.swing.JPanel();
        JButtonImpression = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabelPACS = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabelCR = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(174, 203, 248));
        jLabel4.setText("Aide");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/AjouterPatientPetit.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/AjouterExamenPT.jpg"))); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/AjouterCrP.jpg"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(174, 203, 248));
        jLabel12.setText("Ajouter un patient au SIR ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(174, 203, 248));
        jLabel13.setText("Ajouter un examen à un patient");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(174, 203, 248));
        jLabel14.setText("Ajouter un compte-rendu et le lien PACS");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(174, 203, 248));
        jLabel19.setText("Radiologie");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(174, 203, 248));
        jLabel20.setText("Scanner");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(174, 203, 248));
        jLabel21.setText("IRM");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(174, 203, 248));
        jLabel22.setText("Angiographie");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(174, 203, 248));
        jLabel23.setText("Echoendoscopie");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(174, 203, 248));
        jLabel24.setText("Mammographie");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(174, 203, 248));
        jLabel25.setText("pour pouvoir lui faire des examens");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(174, 203, 248));
        jLabel26.setText("à un examen");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(174, 203, 248));
        jLabel27.setText("Fonctionnalité Recherche ");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(174, 203, 248));
        jLabel28.setText("Permet de rechercher un DMR dans le SIR à partir de certains critères");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(174, 203, 248));
        jLabel29.setText("Date de l'examen");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(174, 203, 248));
        jLabel30.setText("Type de l'examen");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(174, 203, 248));
        jLabel31.setText("Identifiant de l'examen");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(174, 203, 248));
        jLabel32.setText("Accueil du Dossier Médical Radiologique, accès aux examens");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel4)
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel32)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(58, 58, 58)))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel21))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24))))
                            .addGap(36, 36, 36)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel26)))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel31))))))
                        .addGap(260, 260, 260)))
                .addGap(55, 55, 55))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26))
                                    .addComponent(jLabel10))))))
                .addGap(2, 2, 2)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(34, 34, 34))
        );

        jFrameAide.getContentPane().add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(174, 203, 248));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/Logo2.jpg"))); // NOI18N
        Logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        date.setForeground(new java.awt.Color(174, 203, 248));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("Date");
        jPanel4.add(date);

        id.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        id.setForeground(new java.awt.Color(174, 203, 248));
        id.setText("Identifiant");
        jPanel4.add(id);

        name.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        name.setForeground(new java.awt.Color(174, 203, 248));
        name.setText("Nom - Prénom");
        jPanel4.add(name);

        fonction.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fonction.setForeground(new java.awt.Color(174, 203, 248));
        fonction.setText("Fonction");
        jPanel4.add(fonction);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAjouterExamen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/AjouterExamenPT.jpg"))); // NOI18N
        jButtonAjouterExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterExamenActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAjouterExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 80, -1));

        jButtonDeco.setBackground(new java.awt.Color(174, 203, 248));
        jButtonDeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/deco.png"))); // NOI18N
        jButtonDeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecoActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonDeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 40));

        jButtonAide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/help.png"))); // NOI18N
        jButtonAide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAideActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAide, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, 40));

        jButtonAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/Accueil.jpg"))); // NOI18N
        jButtonAccueil.setContentAreaFilled(false);
        jButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccueilActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 60, 50));

        jButtonAjouterPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/AjouterPatientPetit.jpg"))); // NOI18N
        jButtonAjouterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterPatientActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAjouterPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 80, -1));

        jButtonAjouterPersonnel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/ajouterPersonnelPetit.jpg"))); // NOI18N
        jButtonAjouterPersonnel.setEnabled(false);
        jButtonAjouterPersonnel.setInheritsPopupMenu(true);
        jButtonAjouterPersonnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterPersonnelActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAjouterPersonnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 80, 110));

        jButtonAjouterCR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/AjouterCrP.jpg"))); // NOI18N
        jButtonAjouterCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterCRActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAjouterCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 80, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(174, 203, 248));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 203, 248)));
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 322));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(174, 203, 248));
        jLabel2.setText("Patient");

        ident.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ident.setForeground(new java.awt.Color(174, 203, 248));
        ident.setText("ID");

        genre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        genre.setForeground(new java.awt.Color(174, 203, 248));
        genre.setText("Genre");

        nomPat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nomPat.setForeground(new java.awt.Color(174, 203, 248));
        nomPat.setText("Nom");

        prenomPat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prenomPat.setForeground(new java.awt.Color(174, 203, 248));
        prenomPat.setText("Prenom");

        dateNPat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        dateNPat.setForeground(new java.awt.Color(174, 203, 248));
        dateNPat.setText("DateN");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableImage.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTableImage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Image"
            }
        ));
        jTableImage.setAutoscrolls(false);
        jTableImage.setRowHeight(50);
        jTableImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableImageMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableImage);

        jButtonNumImage.setText("Numériser Images");
        jButtonNumImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ident)
                            .addComponent(genre)
                            .addComponent(nomPat)
                            .addComponent(prenomPat)
                            .addComponent(dateNPat)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonNumImage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ident)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomPat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prenomPat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateNPat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jButtonNumImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 203, 248)));
        jPanel9.setPreferredSize(new java.awt.Dimension(80, 160));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTableExamen.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTableExamen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Prioritaire", "ID Examen", "Type Examen", "Date Examen", "Prescripteur", "Responsable Radio", "Compte-Rendu", "Lien PACS"
            }
        ));
        jTableExamen.setRowHeight(20);
        jTableExamen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableExamenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExamen);

        jRadioButtonDate.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonDate.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDate.setText("Par date :");

        jButtonRechercher.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonRechercher.setText("Rechercher");
        jButtonRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercherActionPerformed(evt);
            }
        });

        jTextFieldJour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJour.setText("JJ");
        jTextFieldJour.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldJourFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Rechercher:");
        jLabel3.setToolTipText("");

        jComboBoxType.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jRadioButtonType.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonType.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonType.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonType.setText("Par type : ");

        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setText("Identifiant");
        jTextFieldID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIDFocusGained(evt);
            }
        });

        jRadioButtonID.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonID.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonID.setText("Par identifiant : ");

        jTextFieldAnnee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAnnee.setText("AAAA");
        jTextFieldAnnee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAnneeFocusGained(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");

        jTextFieldMois.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMois.setText("MM");
        jTextFieldMois.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMoisFocusGained(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("/");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButtonDate)
                            .addGap(12, 12, 12)
                            .addComponent(jTextFieldJour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldMois, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(67, 67, 67)
                            .addComponent(jRadioButtonType)
                            .addGap(6, 6, 6)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(73, 73, 73)
                            .addComponent(jRadioButtonID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                            .addComponent(jButtonRechercher))
                        .addComponent(jScrollPane1))
                    .addContainerGap()))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButtonType)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonID)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRechercher))
                        .addComponent(jRadioButtonDate))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 203, 248)));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        Image2.setVisible(true);

        javax.swing.GroupLayout Image2Layout = new javax.swing.GroupLayout(Image2.getContentPane());
        Image2.getContentPane().setLayout(Image2Layout);
        Image2Layout.setHorizontalGroup(
            Image2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Image2Layout.setVerticalGroup(
            Image2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jSplitImage.setRightComponent(Image2);

        Image1.setVisible(true);

        javax.swing.GroupLayout Image1Layout = new javax.swing.GroupLayout(Image1.getContentPane());
        Image1.getContentPane().setLayout(Image1Layout);
        Image1Layout.setHorizontalGroup(
            Image1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Image1Layout.setVerticalGroup(
            Image1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jSplitImage.setLeftComponent(Image1);

        jPanel12.add(jSplitImage);

        jPanel8.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 203, 248)));
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel10.setLayout(new java.awt.BorderLayout());

        JButtonImpression.setText("Impression");
        JButtonImpression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonImpressionActionPerformed(evt);
            }
        });
        jPanel10.add(JButtonImpression, java.awt.BorderLayout.PAGE_END);

        jLabelPACS.setEditable(false);
        jLabelPACS.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPACS.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelPACS.setForeground(new java.awt.Color(174, 203, 248));
        jLabelPACS.setText("PACS");
        jScrollPane3.setViewportView(jLabelPACS);

        jPanel10.add(jScrollPane3, java.awt.BorderLayout.PAGE_START);

        jLabelCR.setEditable(false);
        jLabelCR.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCR.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelCR.setForeground(new java.awt.Color(174, 203, 248));
        jLabelCR.setText("Compte Rendu");
        jScrollPane4.setViewportView(jLabelCR);

        jPanel10.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel10, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1235, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 677, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Medical Imaging Technology - Radiology Information System Exploitation   ");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterExamenActionPerformed
        // TODO add your handling code here:
        if (medecinCo.getFunction().equals(Function.Manipulateur)) {
            AjouterExamen addExamen = new AjouterExamen(dmr);
            addExamen.setVisible(true);
        } else {
            System.out.println("Echec");
            javax.swing.JOptionPane.showMessageDialog(null, "Accès non autorisé");
        }
    }//GEN-LAST:event_jButtonAjouterExamenActionPerformed

    private void jButtonDecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecoActionPerformed
        // TODO add your handling code here:
        Connexion connexion = new Connexion();
        connexion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonDecoActionPerformed

    private void jButtonAideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAideActionPerformed
        // TODO add your handling code here:
        jFrameAide.setVisible(true);
    }//GEN-LAST:event_jButtonAideActionPerformed

    private void jButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccueilActionPerformed
        // TODO add your handling code here:
        AccueilSIR accueil = new AccueilSIR(medecinCo);
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAccueilActionPerformed

    private void jTableExamenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableExamenMouseClicked
        int row = jTableExamen.getSelectedRow();
        int idExam = (int) jTableExamen.getValueAt(row, 1);
        examen = dmr.rechercheExam(idExam);
        System.out.println(examen.getPacsID());
        if (medecinCo.getFunction().equals(Function.Radiologue)) {
            jLabelCR.setText("Aucun Compte rendu");
            jLabelPACS.setText("Aucun Lien Pacs");
            if (examen.getReport() != null) {
                jLabelCR.setText("Compte rendu : \n" + examen.getReport());
            }
            if (examen.getPacsID() != null) {
                jLabelPACS.setText("ID Pacs : \n" + examen.getPacsID());
            }
        } else {
            jLabelCR.setText("Aucun Compte rendu");
            jLabelPACS.setText("Aucun Lien Pacs");
            if (examen.getReport() != null) {
                jLabelCR.setText("Compte rendu : Non Accessible");
            }
            if (examen.getPacsID() != null) {
                jLabelPACS.setText("ID Pacs : Non Accessible");
            }
        }

        Object[][] dataImage = new Object[examen.getPaths().size()][2];
        String[] columnNames = {"Numéro", "Image"};
        for (int i = 0; i < examen.getPaths().size(); i++) {
            dataImage[i][0] = i;
            dataImage[i][1] = examen.getPaths().get(i);
        }
        jTableImage.setModel(new DefaultTableModel(dataImage, columnNames));
    }//GEN-LAST:event_jTableExamenMouseClicked

    private void jTextFieldIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDFocusGained
        // TODO add your handling code here:
        jTextFieldID.setText("");
    }//GEN-LAST:event_jTextFieldIDFocusGained

    private void jTextFieldJourFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldJourFocusGained
        // TODO add your handling code here:
        jTextFieldJour.setText("");
    }//GEN-LAST:event_jTextFieldJourFocusGained

    private void jTextFieldMoisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMoisFocusGained
        // TODO add your handling code here:
        jTextFieldMois.setText("");
    }//GEN-LAST:event_jTextFieldMoisFocusGained

    private void jTextFieldAnneeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAnneeFocusGained
        // TODO add your handling code here:
        jTextFieldAnnee.setText("");
    }//GEN-LAST:event_jTextFieldAnneeFocusGained

    private void jButtonAjouterCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterCRActionPerformed
        // TODO add your handling code here:
        if (medecinCo.getFunction().equals(Function.Radiologue)) {
            AjouterCR addCR = new AjouterCR(examen, dmr);
            addCR.setVisible(true);
        } else {
            System.out.println("Echec");
            javax.swing.JOptionPane.showMessageDialog(null, "Accès non autorisé");
        }
    }//GEN-LAST:event_jButtonAjouterCRActionPerformed

    private void jButtonRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercherActionPerformed
        // TODO add your handling code here:
        ArrayList<Examen> newlisteExam = listeExam;
        if (jRadioButtonDate.isSelected() == true) {
            int j = Integer.parseInt(jTextFieldJour.getText());
            int m = Integer.parseInt(jTextFieldMois.getText());
            int a = Integer.parseInt(jTextFieldAnnee.getText());
            Dates dateE = new Dates(j, m, a);
            newlisteExam = Factory.rechercheListDateExam(newlisteExam, dateE);
        }
        if (jRadioButtonType.isSelected() == true) {
            newlisteExam = Factory.rechercheListTypeExam(newlisteExam, (ExamenType) jComboBoxType.getSelectedItem());
        }
        if (jRadioButtonID.isSelected() == true) {
            newlisteExam = Factory.rechercheListIDExam(newlisteExam, Integer.parseInt(jTextFieldID.getText()));
        }
        Object[][] newDataExam = new Object[newlisteExam.size()][8];
        int k = 0;
        for (int i = 0; i < newlisteExam.size(); i++) {
            newDataExam[k][0] = newlisteExam.get(i).isPrioritaire();
            newDataExam[k][1] = newlisteExam.get(i).getId_examen();
            newDataExam[k][2] = newlisteExam.get(i).getExamenType().toString();
            newDataExam[k][3] = newlisteExam.get(i).getDate();
            newDataExam[k][4] = newlisteExam.get(i).getPrescripteur();
            newDataExam[k][5] = newlisteExam.get(i).getResponsableRadio();
            newDataExam[k][6] = newlisteExam.get(i).getReport();
            newDataExam[k][7] = newlisteExam.get(i).getPacsID();
        }
        jTableExamen.setModel(new DefaultTableModel(newDataExam, liste));
        jTableExamen.getColumnModel().getColumn(0).setCellRenderer(new CouleurCellRenderer());
        jTableExamen.getColumnModel().getColumn(6).setCellRenderer(new ImageCellRenderer());
        jTableExamen.getColumnModel().getColumn(7).setCellRenderer(new ImageCellRenderer());
        if (jRadioButtonType.isSelected() == false && jRadioButtonID.isSelected() == false && jRadioButtonDate.isSelected() == false) {
            System.out.println("error");
            javax.swing.JOptionPane.showMessageDialog(null, "vous n'avez coché aucune case");
        }
    }//GEN-LAST:event_jButtonRechercherActionPerformed

    private void jButtonAjouterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterPatientActionPerformed
        // TODO add your handling code here:
        if (medecinCo.getFunction().equals(Function.Manipulateur)) {
            AjouterPatient addPatient = new AjouterPatient();
            addPatient.setVisible(true);
        } else {
            System.out.println("Echec");
            javax.swing.JOptionPane.showMessageDialog(null, "Accès non autorisé");
        }
    }//GEN-LAST:event_jButtonAjouterPatientActionPerformed

    private void jTableImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableImageMousePressed
        // TODO add your handling code here:
        int row = jTableImage.getSelectedRow();
        int num = (int) jTableImage.getValueAt(row, 0);
        SingleImagePanel image = null;
        try {
            image = new SingleImagePanel(new SourceImage(examen.getPaths().get(num)));
        } catch (IOException ex) {
            Logger.getLogger(AccueilPatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DicomException ex) {
            Logger.getLogger(AccueilPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (evt.getClickCount() == 1) {
            if ((Image1.getComponentCount() == 0) || (Image2.getComponentCount() > 0)) {
                Image1.removeAll();
                Image1.add(image);
                Image1.setBackground(Color.BLACK);
            } else {
                Image2.removeAll();
                Image2.add(image);
                Image2.setBackground(Color.BLACK);
            }
        }
        if (evt.getClickCount() == 2) {
            if (medecinCo.getFunction().equals(Function.Radiologue) || medecinCo.getFunction().equals(Function.Manipulateur)) {
                AfficherImage affImage;
                try {
                    affImage = new AfficherImage(image);
                    affImage.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AccueilPatient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DicomException ex) {
                    Logger.getLogger(AccueilPatient.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } else {
                System.out.println("Echec");
                javax.swing.JOptionPane.showMessageDialog(null, "Accès non autorisé");
            }
        }
    }//GEN-LAST:event_jTableImageMousePressed

    private void JButtonImpressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonImpressionActionPerformed
        // TODO add your handling code here:
        if (medecinCo.getFunction().equals(Function.Radiologue)) {
            if (examen != null) {
                Impression impression = null;
                try {
                    impression = new Impression(dmr, examen);
                    impression.Impression();
                } catch (IOException ex) {
                    Logger.getLogger(AccueilPatient.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("Echec d'impression");
                javax.swing.JOptionPane.showMessageDialog(null, "Veuillez selectionner un examen");
            }
        } else {
            System.out.println("Echec");
            javax.swing.JOptionPane.showMessageDialog(null, "Accès non autorisé");
        }
    }//GEN-LAST:event_JButtonImpressionActionPerformed

    private void jButtonAjouterPersonnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterPersonnelActionPerformed
        // TODO add your handling code here:
        System.out.println("Echec");
        javax.swing.JOptionPane.showMessageDialog(null, "Accès non autorisé");
    }//GEN-LAST:event_jButtonAjouterPersonnelActionPerformed

    private void jButtonNumImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumImageActionPerformed
        // TODO add your handling code here:
        if (medecinCo.getFunction().equals(Function.Radiologue)) {
            if (examen != null) {
                if (examen.getReport() != null) {
                    Numerisation numerisation = new Numerisation(dmr, examen);
                    numerisation.setVisible(true);
                } else {
                    System.out.println("Echec de numérisation");
                    javax.swing.JOptionPane.showMessageDialog(null, "Veuillez remplir le compte rendu");
                }
            } else {
                System.out.println("Echec de numérisation");
                javax.swing.JOptionPane.showMessageDialog(null, "Veuillez selectionner un examen");
            }
        } else {
            System.out.println("Echec");
            javax.swing.JOptionPane.showMessageDialog(null, "Accès non autorisé");
        }

    }//GEN-LAST:event_jButtonNumImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Image1;
    private javax.swing.JInternalFrame Image2;
    private javax.swing.JButton JButtonImpression;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateNPat;
    private javax.swing.JLabel fonction;
    private javax.swing.JLabel genre;
    private javax.swing.JLabel id;
    private javax.swing.JLabel ident;
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonAide;
    private javax.swing.JButton jButtonAjouterCR;
    private javax.swing.JButton jButtonAjouterExamen;
    private javax.swing.JButton jButtonAjouterPatient;
    private javax.swing.JButton jButtonAjouterPersonnel;
    private javax.swing.JButton jButtonDeco;
    private javax.swing.JButton jButtonNumImage;
    private javax.swing.JButton jButtonRechercher;
    private javax.swing.JComboBox<ExamenType> jComboBoxType;
    private javax.swing.JFrame jFrameAide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextPane jLabelCR;
    private javax.swing.JTextPane jLabelPACS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonDate;
    private javax.swing.JRadioButton jRadioButtonID;
    private javax.swing.JRadioButton jRadioButtonType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitImage;
    private javax.swing.JTable jTableExamen;
    private javax.swing.JTable jTableImage;
    private javax.swing.JTextField jTextFieldAnnee;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldJour;
    private javax.swing.JTextField jTextFieldMois;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nomPat;
    private javax.swing.JLabel prenomPat;
    // End of variables declaration//GEN-END:variables
}
