/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sir.ui;

import static java.lang.Boolean.FALSE;
import static java.lang.Boolean.TRUE;
import java.util.ArrayList;
import sir.nf.ExamenType;
import sir.nf.Examen;
import sir.nf.Dates;
import sir.nf.MedicalStaff;
import sir.nf.DMR;
import sir.nf.Factory;
import sir.nf.Function;

/**
 *
 * @author solenn
 */
public class AjouterExamen extends javax.swing.JFrame {

    /**
     * Creates new customizer AjouterExamen
     */
    private DMR dmr;

    public AjouterExamen(DMR dmr) {
        initComponents();
        this.setTitle("AjouterExamen");
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(500, 450);
        this.dmr = dmr;
        IdPatient.setText(Integer.toString(dmr.getId()));
        ArrayList<MedicalStaff> listeMed = Factory.getListeMedecin();
        for(int i = 0; i<listeMed.size(); i++){
            if (listeMed.get(i).getFunction().equals(Function.Radiologue)){
                medSIRBox1.addItem(listeMed.get(i).getName());
                medSIRBox.addItem(listeMed.get(i).getName());
            }
        }
    }
    
    public AjouterExamen() {
        initComponents();
        this.setTitle("AjouterExamen");
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(500, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<ExamenType>(ExamenType.values());
        jButtonSave = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButtonMedSIR = new javax.swing.JRadioButton();
        jRadioButtonMedExt = new javax.swing.JRadioButton();
        medSIRBox = new javax.swing.JComboBox<>();
        nomMedExt = new javax.swing.JTextField();
        jTextFieldAnnee = new javax.swing.JTextField();
        jTextFieldMois = new javax.swing.JTextField();
        jTextFieldJour = new javax.swing.JTextField();
        jTextFieldMinute = new javax.swing.JTextField();
        jTextFieldHeure = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        medSIRBox1 = new javax.swing.JComboBox<>();
        jRadioButtonPrioritaire = new javax.swing.JRadioButton();
        jRadioButtonNumerique = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        IdPatient = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 203, 248));
        jLabel1.setText("Ajouter Examen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(174, 203, 248));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Type d'examen :");

        typeBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        typeBox.setToolTipText("");

        jButtonSave.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonSave.setText("Enregistrer");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Medical Imaging Technology - Radiology Information System Exploitation   ");
        jPanel11.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sir/ui/Ressources/AjouterExamen.jpg"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Date :");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("Prescripteur :");

        jRadioButtonMedSIR.setBackground(new java.awt.Color(174, 203, 248));
        jRadioButtonMedSIR.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonMedSIR.setText("Médecin SIR");

        jRadioButtonMedExt.setBackground(new java.awt.Color(174, 203, 248));
        jRadioButtonMedExt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonMedExt.setText("Médecin Extérieur");

        medSIRBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        nomMedExt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nomMedExt.setText("Nom");
        nomMedExt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomMedExtFocusGained(evt);
            }
        });

        jTextFieldAnnee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAnnee.setText("AAAA");
        jTextFieldAnnee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAnneeFocusGained(evt);
            }
        });

        jTextFieldMois.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMois.setText("MM");
        jTextFieldMois.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMoisFocusGained(evt);
            }
        });

        jTextFieldJour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldJour.setText("JJ");
        jTextFieldJour.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldJourFocusGained(evt);
            }
        });

        jTextFieldMinute.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMinute.setText("Min");
        jTextFieldMinute.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldMinuteFocusGained(evt);
            }
        });

        jTextFieldHeure.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldHeure.setText("H");
        jTextFieldHeure.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldHeureFocusGained(evt);
            }
        });

        jLabel4.setText(":");

        jLabel5.setText("/");

        jLabel6.setText("/");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("PH Responsable : ");

        medSIRBox1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jRadioButtonPrioritaire.setBackground(new java.awt.Color(174, 203, 248));
        jRadioButtonPrioritaire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonPrioritaire.setText("Prioritaire");

        jRadioButtonNumerique.setBackground(new java.awt.Color(174, 203, 248));
        jRadioButtonNumerique.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonNumerique.setText("Examen Numérique");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("Identifiant Patient :");

        IdPatient.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        IdPatient.setText("Identifiant");
        IdPatient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IdPatientFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonPrioritaire)
                .addGap(57, 57, 57)
                .addComponent(jButtonSave)
                .addGap(200, 200, 200))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldJour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldMois, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(medSIRBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jRadioButtonNumerique)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonMedSIR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medSIRBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonMedExt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomMedExt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(IdPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonMedSIR)
                            .addComponent(medSIRBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonMedExt)
                            .addComponent(nomMedExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(medSIRBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonNumerique)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonPrioritaire)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(IdPatient.getText());
        
        int jour = Integer.parseInt(jTextFieldJour.getText());
        int mois = Integer.parseInt(jTextFieldMois.getText());
        int annee = Integer.parseInt(jTextFieldAnnee.getText());
        int heure = Integer.parseInt(jTextFieldHeure.getText());
        int minute = Integer.parseInt(jTextFieldMinute.getText());
        Dates date = new Dates(jour, mois, annee, heure, minute);
        
        ExamenType examenType = (ExamenType) typeBox.getSelectedItem();
        
        MedicalStaff prescripteur = null;
        if (jRadioButtonMedSIR.isSelected() == true && jRadioButtonMedExt.isSelected() == false) {
            String nom = medSIRBox1.getSelectedItem().toString();
            prescripteur = Factory.rechercheMedicalStaff(nom);
        } else if (jRadioButtonMedSIR.isSelected() == false && jRadioButtonMedExt.isSelected() == true) {
            String nom = nomMedExt.getText();
            Factory.creerStaff(nom,"");
            prescripteur = Factory.rechercheMedicalStaff(nom);
        } else if (jRadioButtonMedSIR.isSelected() == false && jRadioButtonMedExt.isSelected() == false) {
            System.out.println("Erreur");
            javax.swing.JOptionPane.showMessageDialog(null, "Vous n'avez coché aucune case pour Prescripteur");
        } else {
            System.out.println("Erreur");
            javax.swing.JOptionPane.showMessageDialog(null, "Vous avez coché 2 cases pour Prescripteur");
        }
        
        String nomPH = medSIRBox.getSelectedItem().toString();
        MedicalStaff ms = Factory.rechercheMedicalStaff(nomPH);
       
        boolean prioritaire = jRadioButtonPrioritaire.isSelected();
        int prio = 0;
        if (prioritaire){
            prio = 1;}
        boolean res = FALSE; 
        if (jRadioButtonNumerique.isSelected()){
            res = Factory.creerExam(id, date, examenType, prescripteur, ms, prio);
        }
        else {
            res = Factory.creerExam(id, date, examenType, prescripteur, ms, prioritaire, "CR Papier");
        }
        if (res == TRUE){
            System.out.println("Ajout");
            javax.swing.JOptionPane.showMessageDialog(null, "L'examen a bien été ajouté");
        }    
        else {
            System.out.println("Echec Ajout");
            javax.swing.JOptionPane.showMessageDialog(null, "Echec lors de l'ajout de l'examen");
        }
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldJourFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldJourFocusGained
        // TODO add your handling code here:
        jTextFieldJour.setText("");
    }//GEN-LAST:event_jTextFieldJourFocusGained

    private void jTextFieldMoisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMoisFocusGained
        // TODO add your handling code here:
        jTextFieldMois.setText("");
    }//GEN-LAST:event_jTextFieldMoisFocusGained

    private void jTextFieldAnneeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAnneeFocusGained
        // TODO add your handling code here:
        jTextFieldAnnee.setText("");
    }//GEN-LAST:event_jTextFieldAnneeFocusGained

    private void jTextFieldHeureFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldHeureFocusGained
        // TODO add your handling code here:
        jTextFieldHeure.setText("");
    }//GEN-LAST:event_jTextFieldHeureFocusGained

    private void jTextFieldMinuteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMinuteFocusGained
        // TODO add your handling code here:
        jTextFieldMinute.setText("");
    }//GEN-LAST:event_jTextFieldMinuteFocusGained

    private void nomMedExtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomMedExtFocusGained
        // TODO add your handling code here:
        nomMedExt.setText("");
    }//GEN-LAST:event_nomMedExtFocusGained

    private void IdPatientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IdPatientFocusGained
        // TODO add your handling code here:
        IdPatient.setText("");
    }//GEN-LAST:event_IdPatientFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdPatient;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonMedExt;
    private javax.swing.JRadioButton jRadioButtonMedSIR;
    private javax.swing.JRadioButton jRadioButtonNumerique;
    private javax.swing.JRadioButton jRadioButtonPrioritaire;
    private javax.swing.JTextField jTextFieldAnnee;
    private javax.swing.JTextField jTextFieldHeure;
    private javax.swing.JTextField jTextFieldJour;
    private javax.swing.JTextField jTextFieldMinute;
    private javax.swing.JTextField jTextFieldMois;
    private javax.swing.JComboBox<String> medSIRBox;
    private javax.swing.JComboBox<String> medSIRBox1;
    private javax.swing.JTextField nomMedExt;
    private javax.swing.JComboBox<ExamenType> typeBox;
    // End of variables declaration//GEN-END:variables

}
