/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sir.ui;

import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import sir.nf.DMR;
import sir.nf.Examen;
import sir.nf.ConvertToDicom;

/**
 *
 * @author solenn
 */
public class Numerisation extends javax.swing.JFrame {

    private Examen exam;
    private DMR dmr;
    private ConvertToDicom convert;

    /**
     * Creates new customizer Numerisation
     */
    public Numerisation(DMR dmr, Examen exam) {
        initComponents();
        this.setTitle("Numeriser Images");
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(500, 450);
        this.exam = exam;
        this.dmr = dmr;
        //jLabelIDPat.setText(Integer.toString(dmr.getId()));
        //jLabelIDExam.setText(exam.getId_examen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEnregistrer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelIDPat = new javax.swing.JLabel();
        jLabelIDExam = new javax.swing.JLabel();
        Image1 = new javax.swing.JLabel();
        Path1 = new javax.swing.JTextField();
        Image2 = new javax.swing.JLabel();
        Path2 = new javax.swing.JTextField();
        Image3 = new javax.swing.JLabel();
        Path3 = new javax.swing.JTextField();
        Image4 = new javax.swing.JLabel();
        Path4 = new javax.swing.JTextField();
        Image5 = new javax.swing.JLabel();
        Path5 = new javax.swing.JTextField();
        Image6 = new javax.swing.JLabel();
        Path6 = new javax.swing.JTextField();
        Parcourir1 = new javax.swing.JButton();
        Parcourir2 = new javax.swing.JButton();
        Parcourir3 = new javax.swing.JButton();
        Parcourir5 = new javax.swing.JButton();
        Parcourir4 = new javax.swing.JButton();
        Parcourir6 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(174, 203, 248));
        jLabel1.setText("Compléter Examen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Medical Imaging Technology - Radiology Information System Exploitation   ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(jLabel2, java.awt.BorderLayout.CENTER);

        add(jPanel11, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(new java.awt.Color(174, 203, 248));

        jButtonEnregistrer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Identifiant Patient :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Identifiant Examen :");

        jLabelIDPat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelIDPat.setText("ID");

        jLabelIDExam.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelIDExam.setText("ID");

        Image1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Image1.setText("Image 1 :");

        Path1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Path1.setText("Chemin1");
        Path1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Path1FocusGained(evt);
            }
        });

        Image2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Image2.setText("Image 2 :");

        Path2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Path2.setText("Chemin2");
        Path2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Path2FocusGained(evt);
            }
        });

        Image3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Image3.setText("Image 3 :");

        Path3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Path3.setText("Chemin3");
        Path3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Path3FocusGained(evt);
            }
        });

        Image4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Image4.setText("Image 4 :");

        Path4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Path4.setText("Chemin4");
        Path4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Path4FocusGained(evt);
            }
        });

        Image5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Image5.setText("Image 5 :");

        Path5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Path5.setText("Chemin5");
        Path5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Path5FocusGained(evt);
            }
        });

        Image6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Image6.setText("Image 6 :");

        Path6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Path6.setText("Chemin6");
        Path6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Path6FocusGained(evt);
            }
        });

        Parcourir1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        Parcourir1.setText("Parcourir");
        Parcourir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parcourir1ActionPerformed(evt);
            }
        });

        Parcourir2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        Parcourir2.setText("Parcourir");
        Parcourir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parcourir2ActionPerformed(evt);
            }
        });

        Parcourir3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        Parcourir3.setText("Parcourir");
        Parcourir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parcourir3ActionPerformed(evt);
            }
        });

        Parcourir5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        Parcourir5.setText("Parcourir");
        Parcourir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parcourir5ActionPerformed(evt);
            }
        });

        Parcourir4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        Parcourir4.setText("Parcourir");
        Parcourir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parcourir4ActionPerformed(evt);
            }
        });

        Parcourir6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11)); // NOI18N
        Parcourir6.setText("Parcourir");
        Parcourir6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parcourir6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Image6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Path6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Image5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Path5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Image4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Path4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Image3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Path3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Image2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Path2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelIDPat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIDExam))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Image1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Path1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Parcourir1)
                    .addComponent(Parcourir2)
                    .addComponent(Parcourir3)
                    .addComponent(Parcourir5)
                    .addComponent(Parcourir4)
                    .addComponent(Parcourir6))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jButtonEnregistrer)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelIDPat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelIDExam))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image1)
                    .addComponent(Path1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parcourir1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image2)
                    .addComponent(Path2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parcourir2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image3)
                    .addComponent(Path3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parcourir3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image4)
                    .addComponent(Path4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parcourir4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image5)
                    .addComponent(Path5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parcourir5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Image6)
                    .addComponent(Path6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Parcourir6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonEnregistrer)
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
        // TODO add your handling code here:
        if (!(Path1.getText().equals("")) && !(Path1.getText().equals("Chemin1"))) {
            String format = Path1.getText().substring(Path1.getText().length() - 4, Path1.getText().length());
            if (format.equals(".jpg")) {
                int i = exam.getPaths().size();
                String PathOutput = "sir/images/image" + dmr.getId() + "_" + exam.getId_examen() + "_" + i + ".dcm";
                exam.getPaths().add(PathOutput);
                File file = new File(Path1.getText());
                File fileOutput = new File(PathOutput);
                convert = new ConvertToDicom(file, fileOutput, dmr.getName(), dmr.getSurname(), dmr.getBirthday().getJavaDate(), dmr.getGender().toString(), Integer.toString(dmr.getId()), exam.getDate().getJavaDate(), exam.getExamenType().toString(), exam.getReport(), exam.getResponsableRadio().getName());
            } else {
                System.out.println("Erreur");
                javax.swing.JOptionPane.showMessageDialog(null, "Format invalide");
            }
        }
        if (!(Path2.getText().equals("")) && !(Path2.getText().equals("Chemin2"))) {
            String format = Path2.getText().substring(Path2.getText().length() - 4, Path2.getText().length());
            if (format.equals(".jpg")) {
                int i = exam.getPaths().size();
                String PathOutput = "sir/images/image" + dmr.getId() + "_" + exam.getId_examen() + "_" + i + ".dcm";
                exam.getPaths().add(PathOutput);
                File file = new File(Path2.getText());
                File fileOutput = new File(PathOutput);
                convert = new ConvertToDicom(file, fileOutput, dmr.getName(), dmr.getSurname(), dmr.getBirthday().getJavaDate(), dmr.getGender().toString(), Integer.toString(dmr.getId()), exam.getDate().getJavaDate(), exam.getExamenType().toString(), exam.getReport(), exam.getResponsableRadio().getName());
            } else {
                System.out.println("Erreur");
                javax.swing.JOptionPane.showMessageDialog(null, "Format invalide");
            }
        }
        if (!(Path3.getText().equals("")) && !(Path3.getText().equals("Chemin3"))) {
            String format = Path3.getText().substring(Path3.getText().length() - 4, Path3.getText().length());
            if (format.equals(".jpg")) {
                int i = exam.getPaths().size();
                String PathOutput = "sir/images/image" + dmr.getId() + "_" + exam.getId_examen() + "_" + i + ".dcm";
                exam.getPaths().add(PathOutput);
                File file = new File(Path3.getText());
                File fileOutput = new File(PathOutput);
                convert = new ConvertToDicom(file, fileOutput, dmr.getName(), dmr.getSurname(), dmr.getBirthday().getJavaDate(), dmr.getGender().toString(), Integer.toString(dmr.getId()), exam.getDate().getJavaDate(), exam.getExamenType().toString(), exam.getReport(), exam.getResponsableRadio().getName());
            } else {
                System.out.println("Erreur");
                javax.swing.JOptionPane.showMessageDialog(null, "Format invalide");
            }
        }
        if (!(Path4.getText().equals("")) && !(Path4.getText().equals("Chemin4"))) {
            String format = Path4.getText().substring(Path4.getText().length() - 4, Path4.getText().length());
            if (format.equals(".jpg")) {
                int i = exam.getPaths().size();
                String PathOutput = "sir/images/image" + dmr.getId() + "_" + exam.getId_examen() + "_" + i + ".dcm";
                exam.getPaths().add(PathOutput);
                File file = new File(Path4.getText());
                File fileOutput = new File(PathOutput);
                convert = new ConvertToDicom(file, fileOutput, dmr.getName(), dmr.getSurname(), dmr.getBirthday().getJavaDate(), dmr.getGender().toString(), Integer.toString(dmr.getId()), exam.getDate().getJavaDate(), exam.getExamenType().toString(), exam.getReport(), exam.getResponsableRadio().getName());
            } else {
                System.out.println("Erreur");
                javax.swing.JOptionPane.showMessageDialog(null, "Format invalide");
            }
        }
        if (!(Path5.getText().equals("")) && !(Path5.getText().equals("Chemin5"))) {
            String format = Path5.getText().substring(Path5.getText().length() - 4, Path5.getText().length());
            if (format.equals(".jpg")) {
                int i = exam.getPaths().size();
                String PathOutput = "sir/images/image" + dmr.getId() + "_" + exam.getId_examen() + "_" + i + ".dcm";
                exam.getPaths().add(PathOutput);
                File file = new File(Path5.getText());
                File fileOutput = new File(PathOutput);
                convert = new ConvertToDicom(file, fileOutput, dmr.getName(), dmr.getSurname(), dmr.getBirthday().getJavaDate(), dmr.getGender().toString(), Integer.toString(dmr.getId()), exam.getDate().getJavaDate(), exam.getExamenType().toString(), exam.getReport(), exam.getResponsableRadio().getName());
            } else {
                System.out.println("Erreur");
                javax.swing.JOptionPane.showMessageDialog(null, "Format invalide");
            }
        }
        if (!(Path6.getText().equals("")) && !(Path6.getText().equals("Chemin6"))) {
            String format = Path6.getText().substring(Path6.getText().length() - 4, Path6.getText().length());
            if (format.equals(".jpg")) {
                int i = exam.getPaths().size();
                String PathOutput = "sir/images/image" + dmr.getId() + "_" + exam.getId_examen() + "_" + i + ".dcm";
                exam.getPaths().add(PathOutput);
                File file = new File(Path6.getText());
                File fileOutput = new File(PathOutput);
                convert = new ConvertToDicom(file, fileOutput, dmr.getName(), dmr.getSurname(), dmr.getBirthday().getJavaDate(), dmr.getGender().toString(), Integer.toString(dmr.getId()), exam.getDate().getJavaDate(), exam.getExamenType().toString(), exam.getReport(), exam.getResponsableRadio().getName());
            } else {
                System.out.println("Erreur");
                javax.swing.JOptionPane.showMessageDialog(null, "Format invalide");
            }
        }
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void Path1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Path1FocusGained
        // TODO add your handling code here:
        Path1.setText("");
    }//GEN-LAST:event_Path1FocusGained

    private void Path2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Path2FocusGained
        // TODO add your handling code here:
        Path2.setText("");
    }//GEN-LAST:event_Path2FocusGained

    private void Path3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Path3FocusGained
        // TODO add your handling code here:
        Path3.setText("");
    }//GEN-LAST:event_Path3FocusGained

    private void Path4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Path4FocusGained
        // TODO add your handling code here:
        Path4.setText("");
    }//GEN-LAST:event_Path4FocusGained

    private void Path5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Path5FocusGained
        // TODO add your handling code here:
        Path5.setText("");
    }//GEN-LAST:event_Path5FocusGained

    private void Path6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Path6FocusGained
        // TODO add your handling code here:
        Path6.setText("");
    }//GEN-LAST:event_Path6FocusGained

    private void Parcourir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parcourir1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        Path1.setText(filename);
    }//GEN-LAST:event_Parcourir1ActionPerformed

    private void Parcourir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parcourir2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        Path2.setText(filename);
    }//GEN-LAST:event_Parcourir2ActionPerformed

    private void Parcourir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parcourir3ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        Path3.setText(filename);
    }//GEN-LAST:event_Parcourir3ActionPerformed

    private void Parcourir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parcourir5ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        Path5.setText(filename);
    }//GEN-LAST:event_Parcourir5ActionPerformed

    private void Parcourir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parcourir4ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        Path4.setText(filename);
    }//GEN-LAST:event_Parcourir4ActionPerformed

    private void Parcourir6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parcourir6ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        Path6.setText(filename);
    }//GEN-LAST:event_Parcourir6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Image3;
    private javax.swing.JLabel Image4;
    private javax.swing.JLabel Image5;
    private javax.swing.JLabel Image6;
    private javax.swing.JButton Parcourir1;
    private javax.swing.JButton Parcourir2;
    private javax.swing.JButton Parcourir3;
    private javax.swing.JButton Parcourir4;
    private javax.swing.JButton Parcourir5;
    private javax.swing.JButton Parcourir6;
    private javax.swing.JTextField Path1;
    private javax.swing.JTextField Path2;
    private javax.swing.JTextField Path3;
    private javax.swing.JTextField Path4;
    private javax.swing.JTextField Path5;
    private javax.swing.JTextField Path6;
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelIDExam;
    private javax.swing.JLabel jLabelIDPat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
