/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sir.ui;

import com.pixelmed.dicom.DicomException;
import com.pixelmed.display.SingleImagePanel;
import com.pixelmed.display.SourceImage;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import sir.nf.ConvertToDicom;
import sir.nf.DMR;
import sir.nf.Impression;
import sir.nf.Gender;
import sir.nf.Dates;

/**
 *
 * @author solenn
 */
public class Test extends javax.swing.JFrame {
    
    
    public Test() throws IOException, DicomException {
        initComponents();
        this.setTitle("Radiographie");
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(670, 550);
        ConvertToDicom convert = new ConvertToDicom();
        //convert.fileToDcm(new File(this.path.getText()), new File("src/sir/alpes/données/" + this.patient.getNom() + "image.dcm"), this.patient.getNom(),this.patient.getDateNaissance(), this.patient.getGenre(), this.patient.getPrenom(), this.patient.getIUP(),"Praticien Test",new Date(),this.jComboBox5.getItemAt(this.jComboBox5.getSelectedIndex()).toString(),this.CompteRendu.getText());
        convert.fileToDcm(new File("src/sir/ui/Ressources/jpg/sinus/sinus1_0000.jpg"), new File("src/sir/ui/Ressources/dicom/sinus0.dcm"), "nomTest","prenomTest", new Date(01,01,2018), "Homme", "ID", new Date(), "TypeExam", "CR");
        SingleImagePanel image = new SingleImagePanel(new SourceImage("src/sir/ui/Ressources/dicom/image-000007.dcm"));
        this.Image.add(image);
        this.Image.setBackground(Color.BLACK);
        this.Image.setSize(100, Image.getY());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Image = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        Image.setBackground(new java.awt.Color(0, 0, 0));
        Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(174, 203, 248)));
        add(Image, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Image;
    // End of variables declaration//GEN-END:variables
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Test().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DicomException ex) {
                    Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
}
